# Generated by Django 4.0.3 on 2022-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
